[workspace]
resolver = "3"

# Oxide currently consists of one kernel crate.
#
# More crates will eventually be added here for:
#
# - memory management
# - drivers
# - filesystem support
# - process management
# - userspace programs
members = ["kernel"]

[package]
name = "oxide"
version = "0.1.0"
edition = "2024"

# The root package is responsible for assembling the final bootable
# Oxide image after the kernel has been compiled.
[build-dependencies]
