[workspace]
resolver = "3"

# Oxide currently consists of one kernel crate.
#
# More crates will eventually be added here for things such as:
#
#        - memory management
#        - drivers
#        - filesystem support
#        - process management
#        - userspace programs
members = ["kernel"]

[package]
name = "oxide"
version = "0.1.0"
edition = "2024"

# The root packages does not need build dependencies yet.
#
# The kernel will be compiled seperately then placed into a 
# bootable Limine image.